# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d23d464fb8af3f7114c91a425cfd1bf3c104535eccc42cd5661d5723061fb90d363cab7985045c6b4f376d872e1186c52cb0481c5cb4ced605f17eaa240e09d2

test:
  secret_key_base: 2ce1c5dfb7286b10b8300e7c4e733f53aa7aca2e9e558f85657e9d7920de01871a9975e79d0ee2806fed41669332f6d8582c40c65eefe33295e883d7f8e11cd4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
